


###
POST http://localhost:3005/login
Content-Type: application/json

{
    "username": "Jim"
}


###

GET http://localhost:3005/testing
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkppbSIsImlhdCI6MTY4NzYxMDQ5NH0.4aa6unil_JP0e1STnibP7V0F1MKxiM9nraMmnuC37yg

